WORK IN PROGRESS integration with Ethers
UniversityDAO/udao pull request #41
Opened 2022-07-15 19:39 UTC by CptAstro

Two main things in this PR:

1. Testing environment for Ethers (this was supposed to be original API but was scrapped). Location in /test
2. Production API for Ethers (not completed). Location in frontend/src/data.

Please feel free to leave any comments if there are any questions

2022-07-16 01:30 UTC, CptAstro commented
**To try out the reading capabilities, do the following:**
1. Start hardhat node: npx hardhat node (in root)
2. Run python deployment script: python auto-deploy-script.py (in /test)
3. Run the EthersTesting.js file: npx hardhat run --network localhost EthersTesting.js (in /test)
4. Spin up the site: npm start (in /frontend)

2022-07-17 23:26 UTC, victor-wei126 commented
@CptAstro Ping me or request a review from anyone else when this PR is ready for review.

2022-07-17 23:30 UTC, CptAstro commented
> @CptAstro Ping me or request a review from anyone else when this PR is ready for review.

Reading functionality is all completed so it can be merged whenever. No proposals/grants load on the site at the moment since the writing part is not complete, but the functionality itself is written and ready to be integrated.

2022-07-17 23:33 UTC, victor-wei126 commented
Awesome, taking a look now. Make sure you change the title to reflect it's not a WIP anymore too.

2022-07-18 00:49 UTC, victor-wei126 requested changes
Looks like most of the essential functionality is there. I'm a bit worried about the efficiency of the implementation though. Right now, it seems like you're fetching the appropriate data in each component. e.g. fetching grants & proposals in `dashboard` component, proposals in `proposals` component, and grants in the `grants` component. Since each call to these `getX()` functions involves a call to `getProposalIDsWithCID()`, there's a lot of duplicate work going on here. I'm wondering if we can do everything in the root component, ie, `App.js`. Here, we can fetch the contract abi's + set provider + getGrants + getProposals. Then we can just pass the data (in a react prop) to the respective component, ie, grants to grants, grants & proposals to dashboard, etc. This would require just one blockchain read operation, compared to the (at least) 4 reads in the current implementation.

Other than that, it looks good besides some smaller issues.. We'll probably need to do more thinking about the efficiency, I haven't fully thought through the above strategy and don't want to jump to it if it ends up causing different problems. Efficiency may be something we want to worry about later, if it ends up being an major issue.

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/data/UDAOApi.js
> +export async function getGrantsOriginal(){
is this the old way we had planned to retrieve grants before carter found the OZ forum? If so, any reason why its kept here instead of deleted?

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/data/UDAOApi.js
> +export async function getGrants(){
add doc

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/data/UDAOApi.js
> +export async function getProposalsOriginal(){
is this the old method?

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/data/UDAOApi.js
> +export async function getProposals(){
add doc

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/data/UDAOApi.js
> +    const proposals = await getProposalIDsWithCID();
I feel like this might be an expensive operation since it involves a read from the blockchain and specifically a search for all ProposalCreated events. Since the blockchain doesn't differentiate between grants and proposals, we shouldn't need to call this function twice since it will return all the `proposalID`s that we need. I'm wondering if there's a way to just call this function once. Perhaps once you get all the `proposalID`s, you can retrieve all the IPFS files, and then separate grants and proposals. Then populate the UI accordingly.

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/pages/proposals.js
> +                setInactiveProposals(proposalData.filter(p => p.active !== 1));
is the change from boolean to int because the activeStatus from solidity is an enum?

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/pages/proposals.js
> +                getProposalIDsWithCID();
why is there a call to this function here?

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/data/config.js
> +import tokenData from "./ContractABIs/UDAOToken.json";
how did you get the contractABIs in here? Jagger had a PR where he changed the compile location of the artifacts. This should be preferred over manually copying over the artifacts, if that's what you did.

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/data/config.js
> +}
All of these functions could be `CONST` I think? Any reason why they are functions?

2022-07-18 00:49 UTC, victor-wei126 commented on frontend/src/data/EthersApi.js
> +    let provider = new ethers.providers.JsonRpcProvider();
Any idea if this is an expensive operation? It's called in every single single function. In fact, the lines of code from 38-40 are the same in each function, grabbing the address, abi, and provider. I'm wondering if there's a more efficient way to do this. Maybe set these in the root, like in `App.js`.

2022-07-18 01:29 UTC, jagger-harris reviewed
Everything looks good to me. But as @victor-wei126 suggested, significant refactoring will have to be done once we get to that point.

I so far have only made 1 file that links everything together, but with the current front end code structure, I struggled to find specific things. We can eventually switch to Vite once the product is in a truly functional state.

2022-07-20 02:55 UTC, CptAstro commented on frontend/src/data/EthersApi.js
> +export function generateHash(jsonObject) {
You're right, it's obsolete. Going ahead and deleting it.

2022-07-20 02:58 UTC, CptAstro commented on frontend/src/data/UDAOApi.js
> +export async function getGrantsOriginal(){
No reason, I had just kept it around while I was testing the new method in case errors arose that required me to use the original method to troubleshoot IPFS problems. Will delete it.

2022-07-20 03:06 UTC, CptAstro commented on frontend/src/data/UDAOApi.js
> +export async function getProposalsOriginal(){
Yeah, same as getGrantsOriginal(), both of which will be deleted.

2022-07-20 03:16 UTC, CptAstro commented on frontend/src/data/UDAOApi.js
> +    const proposals = await getProposalIDsWithCID();
I agree. The only page affected by this problem right now is the dashboard since it loads both proposals and grants simultaneously. When I rewrite the data reading to run only once upon app render (and not on every page load), I will just combine this into one function and then separate grants and proposals via IPFS like you suggested within the App.js file. Then within <Routes> I will pass Proposals and Grants to dashboard.js, Proposals to proposals.js, and Grants to grants.js. That way we avoid we avoid all the unnecessary overhead.

2022-07-20 03:17 UTC, CptAstro commented on frontend/src/data/UDAOApi.js
> +    const proposals = await getProposalIDsWithCID();
Adding on to above comment for clarification: I will be addressing this rendering inefficiency in my next PR.

2022-07-20 03:19 UTC, CptAstro commented on frontend/src/pages/proposals.js
> +                setInactiveProposals(proposalData.filter(p => p.active !== 1));
Yep, prior to this I was storing "active" as an object field on IPFS which was boolean. Grabbing the state from Solidity returns an enum where 1 is equal to active. Because we're classifying anything besides 1 as inactive, no matter what the cause is, I made inactive to !== 1.

2022-07-20 03:21 UTC, CptAstro commented on frontend/src/pages/proposals.js
> +                getProposalIDsWithCID();
Oops haha, was messing around with it when testing and forgot to remove it. Removing it now.

2022-07-20 03:25 UTC, CptAstro commented on frontend/src/data/config.js
> +import tokenData from "./ContractABIs/UDAOToken.json";
Yeah I just manually copied them over because I couldn't access data outside src. I hadn't seen Jaggers PR prior but I will take his code and write it into this PR. His code just pulls it into src, but I'm going to pull it into src/data/ContractABIs like I have it now for organizational purposes.

2022-07-20 03:41 UTC, CptAstro commented on frontend/src/data/config.js
> +}
I wasn't aware you could export constants in Javascript. Changing them to consts.

2022-07-20 03:47 UTC, CptAstro commented on frontend/src/data/EthersApi.js
> +    let provider = new ethers.providers.JsonRpcProvider();
Yep I thought about this too and figured it would be easiest to take care of once I rewrite the data pulling so that it pulls all data once upon app render. Maybe I could just add three more arguments to each of these functions for address, abi, and provider and I pass down the actual values from App.js as props to provide as these three arguments? Since these functions still need to reference those values. Thoughts?

2022-07-20 18:36 UTC, victor-wei126 commented on frontend/src/data/EthersApi.js
> +    let provider = new ethers.providers.JsonRpcProvider();
That's something along the lines of what I was thinking too, just setting all of this once in the App.js "global" react state. I was wondering if it is possible to store these as `const` or global variables in the same api file, and then these functions can reference it? I don't know myself if this makes sense, it might not be, since this is an api file, and you're not running it as a script.

Maybe address this once you get this PR and the next (the one that addresses the main data flow issue) merged, it might be more clear what to do then. I opened an issue so we won't forget about it.

2022-07-20 19:17 UTC, victor-wei126 approved these changes
LGTM. Made a comment about docs, but that can be done in a later PR when we get the coding done and are working on documentation.

2022-07-20 22:12 UTC, merged