Create proposals and cast a vote functions implemented
UniversityDAO/udao pull request #47
Opened 2022-07-25 19:47 UTC by jagger-harris

2022-07-25 20:14 UTC, CptAstro commented
Is there a particular reason why we're using castVoteWithReason as opposed to just castVote?

2022-07-25 21:31 UTC, jagger-harris commented
> Is there a particular reason why we're using castVoteWithReason as opposed to just castVote?

It gives us more options, we can always just pass in a NULL or something.

2022-07-26 00:53 UTC, victor-wei126 commented on frontend/src/data/EthersApi.js
> +export async function propose(transfer, teamAddress, grantAmount, proposalDescription) {
I know this is still a WIP, but we'll probably want to change the parameters here to be: target, value, callData.

2022-07-29 20:37 UTC, CptAstro commented on frontend/src/data/EthersApi.js
> +export async function propose(transfer, teamAddress, grantAmount, proposalDescription) {
To add on to this, the final function should have parameters:

`target, value, callData, proposalDescription, address, abi, provider`

First three are just Victor's changes, and the last three are the additions we'll need to instantiate a contract in ethers

2022-07-29 20:37 UTC, CptAstro commented on frontend/src/data/EthersApi.js
> +  const governor = await ethers.getContract("Governance");
`const governor = new ethers.Contract(address, abi, provider)`

We'll need something along these lines to properly instantiate the governance contract. This is the exact line I used for my reading functions in EthersApi.js, which I've tested and work well

2022-07-29 20:37 UTC, CptAstro commented on frontend/src/data/EthersApi.js
> +  const erc721 = await ethers.getContract("MembershipNFT");
`const erc721 = new ethers.Contract(address, abi, provider)`

Same thing as above comment. Address and Abi will differ between each contract, but provider will be the same between all since provider is just the network that we're using

2022-07-29 20:37 UTC, CptAstro commented on frontend/src/data/EthersApi.js
> +export async function propose(transfer, teamAddress, grantAmount, proposalDescription) {
Essentially every Ethers function will need to pass in address, abi, and provider as arguments.

2022-07-29 20:37 UTC, CptAstro commented on frontend/src/data/EthersApi.js
> +
Everything after the governor.propose() function will probably be good for testing purposes, but definitely isn't essential towards the production build. After we're out of the testing phase, we may want to think about just getting rid of these extraneous lines

2022-07-29 20:46 UTC, CptAstro commented
The next step after completing the functions themselves and working towards actual React integration is grabbing the address and abi for each of the contracts, plus getting the provider that we set in the app.js file so that we can pass these in as arguments. 

For the addresses and abi's, you can just import them from config.js at the top of every page that you need them.

For the provider, you'll have to probably pass it down as props to every page since it's set in app.js (the root). You can do that by something like this for each page:

`{<Proposals activeProposals={activeProposals} inactiveProposals={inactiveProposals} provider={provider}/>}` 

This line in particular would be part of the `element` tag in each of the `Route` components located in app.js. The example I used here is just the proposals page by appending a provider prop and passing in the `provider` variable already present on this page.

2022-07-29 20:59 UTC, victor-wei126 requested changes

2022-07-29 20:59 UTC, victor-wei126 commented on frontend/src/data/EthersApi.js
> +  const voteTx = await ethers.castVoteWithReason(proposalId, support, reason);
I believe the only two essential lines are 106 and 107. Everything else can be removed after you do your local testing. It might be nice to have line 108 tho to grab the receipt and then notify on the frontend via a small message/popup that the transaction is mined, and return the txn hash or something.

2022-07-30 21:40 UTC, jagger-harris commented
Connected the functions together, I also wrote queue and executing the proposals and changed the `getContract` to `Contract`.

2022-07-31 04:03 UTC, CptAstro commented on frontend/src/pages/proposalsApp.js
> +              will they be in the same spot as GOV_ADDRESS or somewhere else?
Yup they're in the same place as `GOV_ADDRESS`. `NFT_ABI/NFT_ADDRESS` represents ERC721 contract, `TOKEN_ABI/TOKEN_ADDRESS` represents ERC20 contract. I named it these since we have MembershipNFT.sol and UDAOToken.sol

2022-07-31 22:39 UTC, victor-wei126 commented on frontend/src/data/EthersApi.js
> +    [transferCalldata],
make all empty arrays so nothing gets executed for now

2022-07-31 22:39 UTC, victor-wei126 commented on frontend/src/data/EthersApi.js
> +    [transferCalldata],
make empty arrays

2022-07-31 22:39 UTC, victor-wei126 commented on frontend/src/data/EthersApi.js
> +    [transferCalldata],
empty arrays

2022-08-01 00:42 UTC, merged