Added tags representing proposal state and added vote error message
UniversityDAO/udao pull request #88
Opened 2022-09-24 22:40 UTC by jagger-harris

Each proposal tag is now meaningful. When a user does not have MetaMask connected and attempts to vote, a proper popup will be displayed.

2022-09-27 21:01 UTC, austin-davis1 requested changes

2022-09-28 00:02 UTC, jagger-harris commented on src/components/Tag.jsx
> +                        : (proposal.state == 2 || proposal.state == 3 || proposal.state == 5 ?
Good catch.

2022-09-28 00:03 UTC, jagger-harris commented on src/components/Tag.jsx
> +  const statuses = ["Pending", "Active", "Canceled", "Failed",
These are just the statuses for now. It will be easy to implement any other tags that we want and passing them as props.

2022-09-28 17:11 UTC, austin-davis1 approved these changes

2022-09-28 17:46 UTC, merged